src/apps/backend/modules/access_token/access_token_service_manager.py
src/apps/backend/modules/account/account_service_manager.py
src/apps/backend/server.py
src/apps/backend/tests/modules/access_token/base_test_access_token.py
src/apps/backend/tests/modules/account/base_test_account.py

_This PR introduces the removal of Service manager used in the boilerplate.
The RestApiServer are directly created in the App now._
NA
NA
_For each manual test case, list the steps to test or reproduce the PR._
NA

chore: Remove service managers

---

Dockerfile

- This fixes Dockerfile with caching layers
- NA
- NA
- NA

fix: Fixing Dockerfile caching issues

---

src/apps/backend/modules/account/internal/account_reader.py
src/apps/backend/modules/account/internal/account_writer.py
src/apps/backend/modules/account/internal/store/account_repository.py
src/apps/backend/modules/account/rest_api/account_rest_api_server.py
src/apps/backend/modules/application/repository.py
src/apps/backend/modules/common/dict_util.py
src/apps/backend/modules/config/config_service.py
src/apps/backend/modules/password_reset_token/internal/password_reset_token_reader.py
src/apps/backend/modules/password_reset_token/internal/password_reset_token_writer.py
src/apps/backend/modules/password_reset_token/internal/store/password_reset_token_repository.py
src/apps/backend/modules/password_reset_token/rest_api/password_reset_token_rest_api_server.py
src/apps/backend/settings/default.py
src/apps/backend/tests/modules/access_token/base_test_access_token.py
src/apps/backend/tests/modules/account/base_test_account.py
src/apps/backend/tests/modules/password_reset_token/base_test_password_reset_token.py

This adds support for caching database connections amongst repositories
- NA
- NA
- NA

feat: Add support for database connection caching

---

Makefile
src/apps/backend/gunicorn_config.py

This fixes following issues:
- https://github.com/orgs/jalantechnologies/projects/9/views/1?pane=issue&itemId=72477789
- https://github.com/orgs/jalantechnologies/projects/9/views/1?pane=issue&itemId=72477941
- NA
- NA
- NA

fix: HTTP deadlocks and request logger

---

Makefile

- This fixes issues with scripts where importing local modules was causing `ModuleNotFound` error
- NA
- NA
- NA

fix: Fix issues with scripts not able to resolve local modules

---

.github/workflows/clean_on_delete.yml
.github/workflows/clean_on_dispatch.yml
.github/workflows/clean_on_pr_closed.yml
.github/workflows/preview_on_dispatch.yml
.github/workflows/preview_on_pr_update.yml
.github/workflows/production_on_push.yml
src/apps/frontend/routes/protected.tsx

_This PR updated the version of workflow to latest(2.5)._
NA
NA
_For each manual test case, list the steps to test or reproduce the PR._
NA

chore: update workflow version to 2.5

---

README.md

_This PR is about updating the README file according to the new changes made into the project._
_NA._
- NA
- NA

Chore: Update README file

---

src/apps/frontend/contexts/account.provider.tsx
src/apps/frontend/services/account.service.ts
src/apps/frontend/services/auth.service.ts
src/apps/frontend/types/auth.ts

Missed styling changes on the main branch.

style: reformat files

---

Makefile

_This PR addressess on adding test checks on the test cases that are printing on the Actions._
- Prints all test cases briefly on test checks
- `-s`: For standard output (print statements) to be displayed in real-time during test
-  `-x`: Stops the test run immediately after the first failure.
- `-v`: Increases verbosity, showing detailed test names and statuses. 
_NA_
- NA
- Manually tested the changes on `docker compose -f docker-compose.test.yml up` .

fix: Add test checks

---

src/apps/backend/modules/logger/internal/loggers.py

Fixing a typo in loggers.py file in loggers.internal regarding debug function
Manual Testing : Tested by running all logger functions on device by temporarily adding them in server.py

Fixing typo in loggers.py file

---

lib/kube/preview/deployment.yaml
lib/kube/production/deployment.yaml

_This PR updates the pods requesting limits._
- Since this is an bootstrap product and the pods on node requesting more memory and CPU Usage leading to excess load on the node. Minimizing the pod request and can be adjustable for the product team based on the project needs
_NA._
- NA
- NA

fix: Modified pod request limits

---

lib/kube/shared/service.yaml

_This PR address fixing web-app service in `service.yaml`._
_NA._
- NA
_For each manual test case, list the steps to test or reproduce the PR._
- NA

fix: add service for web-app

---

lib/kube/production/temporal-deployment.yaml

_This PR addresses adding temporal deployment for `production`._
_NA_

feat: add temporal deployment for production

---

lib/kube/preview/temporal-deployment.yaml
lib/kube/production/temporal-deployment.yaml

_This PR addresses updating pod limits on `temporal-deployment.yaml` and adding `nodeAffinity` to the deployments._
_NA_

feat: update temporal deployments

---

lib/kube/shared/service.yaml

_This PR resolves the temporal connection with postgresql from Digital Ocean._
_NA_

fix: update temporal-grpc service name in service.yaml

---

.github/workflows/clean_on_delete.yml
.github/workflows/clean_on_dispatch.yml
.github/workflows/clean_on_pr_closed.yml
.github/workflows/preview_on_dispatch.yml
.github/workflows/preview_on_pr_update.yml
.github/workflows/production_on_push.yml

_This PR addresses modifying the release tag from `v2.5` to `v2.6` ._
_NA._

chore: upgrade ci to latest release - v2.6

---

.github/workflows/clean_on_delete.yml
.github/workflows/clean_on_dispatch.yml
.github/workflows/clean_on_pr_closed.yml
.github/workflows/preview_on_dispatch.yml
.github/workflows/preview_on_pr_update.yml
.github/workflows/production_on_push.yml

Update to ci v3.0 ([ref](https://github.com/jalantechnologies/github-ci/releases/tag/v3.0))

build: update to ci v3.0

---

.github/workflows/clean_on_delete.yml
.github/workflows/clean_on_dispatch.yml
.github/workflows/clean_on_pr_closed.yml
.github/workflows/preview_on_dispatch.yml
.github/workflows/preview_on_pr_update.yml
.github/workflows/production_on_push.yml

_Fix issue where it was printing wrong dashboard url in PR preview comment._

chore: update dashboard url

---

lib/kube/preview/temporal-deployment.yaml
lib/kube/production/temporal-deployment.yaml
lib/kube/shared/service.yaml

_Update temporal-deployment label from `$KUBE_APP-temporal` to `temporal`._
_NA._

fix: update temporal label in temporal-deployment.yaml

---

lib/kube/shared/ingress.yaml
lib/kube/shared/service.yaml

_This PR updates temporal service names in `service.yaml` and `ingress.yaml`._
_Please document any change in database schema made part of this PR._

fix: update temporal service names

---

tests/modules/account/test_account_api.py
tests/modules/authentication/test_password_reset_token_api.py

Refactor: update import paths for SMS and Email services to notification module
**Description**
This PR fixes incorrect import paths in test files that were causing `ModuleNotFoundError` during test execution. The imports were referencing the outdated `modules.communication` path, but the actual services are located in `modules.notification`. This change updates the import statements to use the correct module paths, ensuring tests can run successfully without import errors.
**Database schema changes**
No database schema changes are made as part of this PR.
---
**Automated Tests**
* No new automated test cases added.
* Fixed existing test imports to resolve `ModuleNotFoundError`.
* All existing test functionality remains unchanged.
**Manual Test Cases**
1. **Run full test suite**
* Execute …

Refactor: update import paths for SMS and Email services to notification module

---

README.md
docs/backend-architecture.md

Add documentation for the backend architecture of our Flask-React boilerplate

docs: add backend architecture doc

---

.github/workflows/clean_on_delete.yml
.github/workflows/clean_on_dispatch.yml
.github/workflows/clean_on_pr_closed.yml
.github/workflows/preview_on_dispatch.yml
.github/workflows/preview_on_pr_update.yml
.github/workflows/production_on_push.yml

**Why these changes are required**
Before these changes, the pipeline was triggered for both draft and undraft PRs, including those with failing test cases from the previous run. This caused unnecessary GitHub Actions usage and wasted pipeline minutes.
**With these optimizations:**
- The pipeline will only trigger for undraft PRs with passing test cases.
- Draft PRs will be skipped.
- The deploy stage will be skipped for undraft PRs with failing test cases.
**Manual Test Cases Performed**
**1)Draft PR with failing test cases**
- Raised a PR from the test branch with the base branch as namra/chore/ci-preview-deploy-conditions.
- Marked the branch as Draft.
- In GitHub Actions, the pipeline was skipped as expected
**2)Draft PR with passing test cases**
- Raised a PR from the test branch …

Update preview workflow to handle draft/undraft PRs and ensure successful test execution

---

.github/workflows/permanent_preview.yml
README.md

_This Pull Request introduces a new workflow `permanent_preview.yml` to support a **Permanent Preview App.**_
- Deploys the app from the `main` branch.
- Uses **preview environment** configs (API keys, DB, etc..).
- Keeps the app always updated with the latest changes from `main`.
- Updates the `README` with an **Environment & URLs** section so engineers can quickly find app endpoints.
_NA._
- Manually triggered workflow from the feature branch(`punith/feat/add-permanent-preview-app`)
- Verified deployment of **Permanent Preview App** is deployed at `preview--flask-react-template.platform.bettrhq.com`

feat: add permanent preview app
